### ISSUE TITLE
Erosion brush on not waterlogged block that is default waterlogged makes block waterlogged

### ISSUE THREAD

**Issue by sw3aterCS** [14ercooper/14erEdit#173] opened 2021-05-01 04:56 UTC
**Describe the bug**
Applying an erosion brush to a block that is not waterlogged but places default waterlogged re-waterlogs the block in error.

**To Reproduce**
1. Place some dead fire coral, not waterlogged.
2. Apply cut or other erosion brush to area containing said coral.
3. See the coral become waterlogged, which is bad.

**Expected behavior**
The coral. It shouldn't become waterlogged.

**Attempted Workarounds (please note if any workarounds were successful**
Successful workaround: Replace waterlogged coral with not waterlogged coral by hand, manually.

**System (please complete the following information):**
 - Spigot Version: Not sure, go ask Forite, it's his server we're doing this on.
 - Java Version: 11
 - Using Megaserver or Release Version: Using the latest 14erEdit beta

**Comment by erismc** [comment] 2021-05-01 11:13
I think this is also true of Voxel Sniper brushes and is inherited from that, also a problem with double slabs, basically that the erosion algorithms don't keep block data (separate bug report here for the double slab issue https://github.com/14ercooper/14erEdit/issues/127#issue-842825792 )

**Comment by 14ercooper** [comment] 2021-05-30 16:47
Duplicate of #127

**Closed by 14ercooper** 2021-05-30 16:47 UTC
Labels: bug
